### ISSUE TITLE
Add toMatch

### ISSUE THREAD

**Issue by sz-piotr** [dethcrypto/earl#162] opened 2021-12-31 12:50 UTC
It will be equivalent to
```ts
expect('xxx').toEqual(expect.stringMatching(/x/))
```

**Comment by krzkaczor** [comment] 2022-01-09 00:04
Duplicate of https://github.com/dethcrypto/earl/issues/147 

Yeah, i agree that we should have such a validator. The name pattern should conform to what we decide in #147

**Closed by krzkaczor** 2022-01-09 00:04 UTC
